--Adicionando usuarios
INSERT INTO USUARIO (LOGIN, PASSWORD) VALUES ('Ana', '$2a$10$CuGIuOYkPDdHK55huIuPXOKtLDutYfRYgzAAFBr5xcEMBbN5OSfli');
INSERT INTO USUARIO (LOGIN, PASSWORD) VALUES ('TechCorp', '$2a$10$38PFTgFgxDaMPllzUMAOfO4T//xLyEVxD8czQhi0wCv7TyT7M3tV6');

--Adicionando os papeis
INSERT INTO ROLE (NOME) VALUES ('ROLE_ADMIN');
INSERT INTO ROLE (NOME) VALUES ('ROLE_USER');

--Relacionando os usuarios ao seus papeis
INSERT INTO USUARIO_ROLES (USUARIO_ID, ROLES_ID) VALUES (1, 1);
INSERT INTO USUARIO_ROLES (USUARIO_ID, ROLES_ID) VALUES (2, 2);

--Criando as pessoas (fisica e juridica) e relacionando aos seus usuarios
INSERT INTO TB_PESSOA (USUARIO_ID, TIPO, EMAIL, TELEFONE, NOME, CPF, RAZAO_SOCIAL, CNPJ) VALUES (1, 'F', 'ANA.SOUZA@EMAIL.COM', '(63)98888-7777', 'Ana Souza', '578.470.310-27', NULL, NULL);
INSERT INTO TB_PESSOA (USUARIO_ID, TIPO, EMAIL, TELEFONE, NOME, CPF, RAZAO_SOCIAL, CNPJ) VALUES (2, 'J', 'COMPRAS@TECHCORP.COM', '(62)3333-4444', NULL, NULL, 'TechCorp', '72.213.845/0001-76');

--Inserindo os produtos
INSERT INTO PRODUTO (DESCRICAO, VALOR, URL_IMAGEM) VALUES ('Notebook Gamer', 7500.00, 'https://www.notebookcheck.net/fileadmin/Notebooks/News/_nc3/Dell_G15_family_photo_2.jpg');
INSERT INTO PRODUTO (DESCRICAO, VALOR, URL_IMAGEM) VALUES ('Mouse sem fio', 150.00, 'https://images7.kabum.com.br/produtos/fotos/104587/mouse-logitech-mx-master-3-sem-fio-recarregavel-tecnologia-flow-unifying-4000dpi-910-005647_1613400718_gg.jpg');
INSERT INTO PRODUTO (DESCRICAO, VALOR, URL_IMAGEM) VALUES ('Celular', 3500.00, 'https://cdn.mos.cms.futurecdn.net/vBYZnyCh4VTtxmsfz2C9BA-1200-80.jpg');
INSERT INTO PRODUTO (DESCRICAO, VALOR, URL_IMAGEM) VALUES ('Mouse-Pad', 50.00, 'https://images.fravega.com/f1000/429986f40a3b8d3cc52717515b07af78.jpg');

--Inserindo as vendas e relacionando os clientes(pessoas)
INSERT INTO VENDA (DATA, PESSOA_ID) VALUES ('2025-10-04', 1);
INSERT INTO VENDA (DATA, PESSOA_ID) VALUES ('2025-10-05', 2);
INSERT INTO VENDA (DATA, PESSOA_ID) VALUES ('2025-10-06', 2);

--Inserindo e relacionando as vendas com os produtos
INSERT INTO ITEM_VENDA (QUANTIDADE, VALOR_UNITARIO, PRODUTO_ID, VENDA_ID) VALUES (1.0, 7500.00, 1, 1);
INSERT INTO ITEM_VENDA (QUANTIDADE, VALOR_UNITARIO, PRODUTO_ID, VENDA_ID) VALUES (2.0, 150.00, 2, 1);
INSERT INTO ITEM_VENDA (QUANTIDADE, VALOR_UNITARIO, PRODUTO_ID, VENDA_ID) VALUES (2.0, 3500.00, 3, 2);
INSERT INTO ITEM_VENDA (QUANTIDADE, VALOR_UNITARIO, PRODUTO_ID, VENDA_ID) VALUES (1.0, 150.00, 2, 3);